[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Quasi quotation system for ecmascript"
documentation = "https://rustdoc.swc.rs/swc_ecma_quote_macros/"
edition       = "2021"
license       = "Apache-2.0"
name          = "swc_ecma_quote_macros"
repository    = "https://github.com/swc-project/swc.git"
version       = "1.0.0"

[lib]
bench      = false
proc-macro = true

[dependencies]
anyhow      = { workspace = true }
proc-macro2 = { workspace = true }
quote       = { workspace = true }
syn         = { workspace = true }

swc_atoms         = { version = "2.0.0", path = "../swc_atoms" }
swc_common        = { version = "1.0.0", path = "../swc_common" }
swc_ecma_ast      = { version = "1.0.0", path = "../swc_ecma_ast" }
swc_ecma_parser   = { version = "1.0.1", path = "../swc_ecma_parser" }
swc_macros_common = { version = "1.0.0", path = "../swc_macros_common" }
