[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "JsDoc parser writen in rust"
documentation = "https://rustdoc.swc.rs/jsdoc/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "jsdoc"
repository    = { workspace = true }
version       = "1.0.0"

[lib]
bench = false

[features]
serde-impl = ["serde"]

[dependencies]
nom   = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }

swc_atoms  = { version = "2.0.0", path = "../swc_atoms" }
swc_common = { version = "1.0.0", path = "../swc_common" }

[dev-dependencies]
anyhow  = { workspace = true }
dashmap = { workspace = true }

swc_ecma_ast    = { version = "1.0.0", path = "../swc_ecma_ast" }
swc_ecma_parser = { version = "1.0.1", path = "../swc_ecma_parser" }
testing         = { version = "1.0.0", path = "../testing" }
